// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzc8gRRwZ3F4fTqcok1TzeIiao6GNvdo',
    appId: '1:559643969918:web:7f2b4ad113aa77ef1f4b2f',
    messagingSenderId: '559643969918',
    projectId: 'fir-flutter-hybrd',
    authDomain: 'fir-flutter-hybrd.firebaseapp.com',
    storageBucket: 'fir-flutter-hybrd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrNQ0KKTlv3Z1oIBlpmu_NNkaZIyzlSc',
    appId: '1:559643969918:android:9055b7e01bf6bdda1f4b2f',
    messagingSenderId: '559643969918',
    projectId: 'fir-flutter-hybrd',
    storageBucket: 'fir-flutter-hybrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVyYFxFx5lc9yGxvmnujIn-55Yr4nJ8ZM',
    appId: '1:559643969918:ios:be1a89a44352d0281f4b2f',
    messagingSenderId: '559643969918',
    projectId: 'fir-flutter-hybrd',
    storageBucket: 'fir-flutter-hybrd.appspot.com',
    iosClientId: '559643969918-s9uo8mpjvefmfci2tuoir527brovm63m.apps.googleusercontent.com',
    iosBundleId: 'id.samyutomo.app.hybrdApp',
  );
}
